# Generated by Django 2.2.18 on 2022-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='describe', max_length=100000),
            preserve_default=False,
        ),
    ]
