# Generated by Django 2.2.18 on 2022-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0007_auto_20220216_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Image', upload_to=None, verbose_name=''),
            preserve_default=False,
        ),
    ]
