# Generated by Django 2.2.18 on 2022-02-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0008_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
