# Generated by Django 2.2.18 on 2022-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0009_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Image', upload_to=''),
            preserve_default=False,
        ),
    ]
