# Generated by Django 2.2.18 on 2022-02-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0016_auto_20220220_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='User',
            new_name='user',
        ),
    ]
