# Generated by Django 2.2.18 on 2022-02-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0022_auto_20220220_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
